"""
This type stub file was generated by cyright, and then edited by hand
"""

from typing import TypeAlias
from numpy import uint8, uint16
from numpy.typing import NDArray

PyleneCompatArray : TypeAlias = NDArray[uint8] | NDArray[uint16]


def max_pool_filter(image: NDArray, kernel_height: int, kernel_width: int) -> list[tuple[float, float]]:
    """Perform a maxpool operation on the target image
    
    Inputs:
        image: image on which to perform the maxpool operation
        kernel_height: height of the maxpool kernel
        kernel_width: width of the maxpool kernel

    Outputs:
        a list of (y, x) positions for the maxes

    Note:
        supported image formats are 8b, 16b and float32. Other formats
            are converted to float32.
    """
    ...

def detect_spots_as_boxes(image: NDArray, max_elems: int = 15, noise_level: float = 4., epsilon: float = 1.) -> list[tuple[float, float, float, float, float, float]]:
    """
    Detect spots (local level set search implementation).

    The output corresponds to a list of detected boxes.

    Inputs:
        image: Input image. Supported formats are 8b, 16b and float32.
            Other formats are converted to float32.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.
        noise_level: Used in the method threshold. Assumed image noise level.
        epsilon: Used in the method threshold. Target theorical number of
            false detections on a random image of the same size.

    Outputs:
        A list of tuples (one tuple per detected box). The tuples contain
            (y1, x1, y2, x2, size, score), where size if the number of pixels
            in the detected level set, and score is the log(NFA) value that was
            used in the threshold (lower means more contrasted spot)
    """
    ...

def detect_spots_as_boxes_maxtree(image: PyleneCompatArray, max_elems: int = 15, noise_level: float = 4., epsilon: float = 1.) -> list[tuple[float, float, float, float, float, float]]:
    """
    Detect spots (Max-Tree implementation).

    The output corresponds to a list of detected boxes.

    Inputs:
        image: Input image. Supported formats are unsigned 8b, 16b.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.
        noise_level: Used in the method threshold. Assumed image noise level.
        epsilon: Used in the method threshold. Target theorical number of
            false detections on a random image of the same size.

    Outputs:
        A list of tuples (one tuple per detected box). The tuples contain
            (y1, x1, y2, x2, size, score), where size if the number of pixels
            in the detected level set, and score is the log(NFA) value that was
            used in the threshold (lower means more contrasted spot)
    """
    ...

def detect_spots_as_mask(image: NDArray, max_elems: int = 15, noise_level: float = 4., epsilon: float = 1.) -> NDArray[uint8]:
    """
    Detect spots (local level set search implementation).

    The output corresponds to a detected mask. All pixels part of a
    detection are colored in the mask. The main use of this method
    is for educational purposes, as it enables to visualize the boundaries
    of the detections. 

    Inputs:
        image: Input image. Supported formats are 8b, 16b and float32.
            Other formats are converted to float32.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.
        noise_level: Used in the method threshold. Assumed image noise level.
        epsilon: Used in the method threshold. Target theorical number of
            false detections on a random image of the same size.

    Outputs:
        A list of tuples (one tuple per detected box). The tuples contain
            (y1, x1, y2, x2, size, score), where size if the number of pixels
            in the detected level set, and score is the log(NFA) value that was
            used in the threshold (lower means more contrasted spot)
    """
    ...

def detect_spots_detailed(image: NDArray, max_elems: int = 15, noise_level: float = 4., epsilon: float = 1.) -> list[list[tuple[float, float, float]]]:
    """
    Detect spots (local level set search implementation).

    The output corresponds to a list of pixels for each detection.

    Inputs:
        image: Input image. Supported formats are 8b, 16b and float32.
            Other formats are converted to float32.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.
        noise_level: Used in the method threshold. Assumed image noise level.
        epsilon: Used in the method threshold. Target theorical number of
            false detections on a random image of the same size.

    Outputs:
        A list of lists (one list per detected box). The list contains
            (y, x, score), where y, x is a pixel part of the detection
            and score is the log(NFA) value that was used in the
            threshold (lower means more contrasted spot). The same score
            is contained for all pixels of a given detection.
    """
    ...

def detect_spots_as_mask_maxtree(image: PyleneCompatArray, max_elems: int = 15, noise_level: float = 4., epsilon: float = 1.) -> NDArray[uint8]:
    """
    Detect spots (Max-Tree implementation).

    The output corresponds to a detected mask. All pixels part of a
    detection are colored in the mask. The main use of this method
    is for educational purposes, as it enables to visualize the boundaries
    of the detections. 

    Inputs:
        image: Input image. Supported formats are 8b a,d 16b.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.
        noise_level: Used in the method threshold. Assumed image noise level.
        epsilon: Used in the method threshold. Target theorical number of
            false detections on a random image of the same size.

    Outputs:
        A list of tuples (one tuple per detected box). The tuples contain
            (y1, x1, y2, x2, size, score), where size if the number of pixels
            in the detected level set, and score is the log(NFA) value that was
            used in the threshold (lower means more contrasted spot)
    """
    ...

def detect_spots_detailed_maxtree(image: PyleneCompatArray, max_elems: int = 15, noise_level: float = 4., epsilon: float = 1.) -> list[list[tuple[float, float, float]]]:
    """
    Detect spots (Max-Tree implementation).

    The output corresponds to a list of pixels for each detection.

    Inputs:
        image: Input image. Supported formats are 8b and 16b.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.
        noise_level: Used in the method threshold. Assumed image noise level.
        epsilon: Used in the method threshold. Target theorical number of
            false detections on a random image of the same size.

    Outputs:
        A list of lists (one list per detected box). The list contains
            (y, x, score), where y, x is a pixel part of the detection
            and score is the log(NFA) value that was used in the
            threshold (lower means more contrasted spot). The same score
            is contained for all pixels of a given detection.
    """
    ...

def remove_small_sets(image: NDArray, max_elems=15) -> NDArray:
    """
    Remove small level sets from the image (Local level set search implementation).

    It does flatten pixels that are part of small sets.

    Inputs:
        image: Input image. Supported formats are 8b, 16b and float32.
            Other formats are converted to float32.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.

    Outputs:
        An image where all found level sets matching the size criteria are
            replaced with flat regions of the lowest value in the
            corresponding level set.
    """
    ...

def remove_small_sets_maxtree(image: PyleneCompatArray, max_elems: int = 15) -> NDArray:
    """
    Remove small level sets from the image (Max-Tree implementation).

    It does flatten pixels that are part of small sets.

    Inputs:
        image: Input image. Supported formats are 8b and 16b.
        max_elems: The maximum number of pixels allowed in a level set
            during the search.

    Outputs:
        An image where all found level sets matching the size criteria are
            replaced with flat regions of the lowest value in the
            corresponding level set.
    """
    ...

def get_level_stats(image: PyleneCompatArray) -> tuple[list[int], list[int]]:
    """
    Get statistics about the level sets of an image.

    The goal of this function is to visualize the distribution
    of deltas between level sets for a given image.

    Inputs:
        image: Input image. Supported formats are 8b, 16b.

    Outputs:
        A tuple containing:
            A list of number of pixels (size of a level set)
            A list of intensity deltas with their parent level set 
    """
    ...

